### ISSUE TITLE
Dosent work at all

### ISSUE THREAD

**Issue by syskill-the-coder** [Itzsten/Python-MBR-Overwriting#1]
lol nothing in here works

**Comment by Itzsten** [comment]
run it as administrator

**Comment by winapiadmin** [comment]
Why? this code working:
from ByteBeat import *
ByteBeat.Play(
    't>>5|(t<<3)+12*t*(t>>13|(t>>1|t>>10|t>>2)&t>>8)', # The mathematical input, as a string.
    13,           # The amount of seconds to play.
    1000,       # KiloHertz (kHz) for the ByteBeat.
    True        # Wait until the ByteBeat finished or not.
)
