### ISSUE TITLE
Conflict name of 'ctypes'

### ISSUE THREAD

**Issue by winapiadmin** [Itzsten/Python-MBR-Overwriting#3]
The ctypes.py may be conflicting of the ctypes.py library of Python.

**Comment by Itzsten** [comment]
It is not intended to be imported, the name is used for a basic and short description of what it uses.

**Comment by winapiadmin** [comment]
Yes, it may be conflicted if you use ctypes instead of pywin32.

**Comment by winapiadmin** [comment]
But the ctypes.py referenced by itself, if you run the ctypes.py it will error.
